### ISSUE TITLE
Contact number is increasing with no new contacts

### ISSUE THREAD

**Issue by fluflo** [SecureTagForApproachRecognition/star-sdk-android#2]
When sitting next to the same person, the number of contacts is increasing. On both devices.

**Comment by ubamrein** [comment]
Hey thanks for reporting! 

We probably need to update the documentation, but this behaviour is indeed intended for two reasons:
1. We may choose to only flag someone as "possibly" infected if this persons spends more than `n` minutes with some who was tested positive. Hence we need multiple samples to have a feeling of how long the contact lasted
2. We have no possibility beforehand to know, if someone is the same device. First, both platforms are randomizing their MAC-Address, which means, your device may see "another" device although it's actually the same, just with another MAC-Address [(1)](https://www.bluetooth.com/blog/bluetooth-technology-protecting-your-privacy/). Second, the tokens we generate are non correlated [(2)](https://en.wikipedia.org/wiki/HMAC) , which means we have no chance of knowing if a "contact" is the same. This only gets possible, after someone who was tested positive releases their secret key, since then we can derive the token from the secret key and the counter (c.f. [STAR-Dokumentation](https://github.com/SecureTagForApproachRecognition/star-sdk-documentation) for more detailed infos about the algorithm used)

I will also forward the issue to the NextStep-App team to improve naming!
